import type { IndicatorMeta } from "./types";

export const INDICATORS: IndicatorMeta[] = [
  {
    slug: "gdp-growth",
    title: "GDP growth",
    unit: "annual %",
    kind: "pct",
    code: "NY.GDP.MKTP.KD.ZG",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/NY.GDP.MKTP.KD.ZG",
    decimals: 1,
  },
  {
    slug: "gdp-per-capita",
    title: "GDP per capita",
    unit: "constant 2015 US$",
    kind: "usd",
    code: "NY.GDP.PCAP.KD",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/NY.GDP.PCAP.KD",
    decimals: 0,
  },
  {
    slug: "inflation",
    title: "Inflation (CPI)",
    unit: "annual %",
    kind: "pct",
    code: "FP.CPI.TOTL.ZG",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/FP.CPI.TOTL.ZG",
    decimals: 1,
  },
  {
    slug: "broad-money",
    title: "Broad money",
    unit: "% of GDP",
    kind: "pct",
    code: "FM.LBL.BMNY.GD.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/FM.LBL.BMNY.GD.ZS",
    decimals: 1,
  },
  {
    slug: "gross-capital-formation",
    title: "Gross capital formation",
    unit: "% of GDP",
    kind: "pct",
    code: "NE.GDI.TOTL.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/NE.GDI.TOTL.ZS",
    decimals: 1,
  },
  {
    slug: "external-debt",
    title: "External debt",
    unit: "% of GNI",
    kind: "pct",
    code: "DT.DOD.DECT.GN.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/DT.DOD.DECT.GN.ZS",
    decimals: 1,
  },
  {
    slug: "exports",
    title: "Exports of goods & services",
    unit: "% of GDP",
    kind: "pct",
    code: "NE.EXP.GNFS.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/NE.EXP.GNFS.ZS",
    decimals: 1,
  },
  {
    slug: "imports",
    title: "Imports of goods & services",
    unit: "% of GDP",
    kind: "pct",
    code: "NE.IMP.GNFS.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/NE.IMP.GNFS.ZS",
    decimals: 1,
  },
  {
    slug: "current-account",
    title: "Current account balance",
    unit: "% of GDP",
    kind: "pct",
    code: "BN.CAB.XOKA.GD.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/BN.CAB.XOKA.GD.ZS",
    decimals: 1,
  },
  {
    slug: "reserves-months",
    title: "Foreign reserves",
    unit: "months of imports",
    kind: "months",
    code: "FI.RES.TOTL.MO",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/FI.RES.TOTL.MO",
    decimals: 1,
  },
  {
    slug: "remittances",
    title: "Personal remittances received",
    unit: "% of GDP",
    kind: "pct",
    code: "BX.TRF.PWKR.DT.GD.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/BX.TRF.PWKR.DT.GD.ZS",
    decimals: 1,
  },
  {
    slug: "population",
    title: "Population",
    unit: "total",
    kind: "count",
    code: "SP.POP.TOTL",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SP.POP.TOTL",
    decimals: 0,
  },
  {
    slug: "exchange-rate",
    title: "Exchange rate (official)",
    unit: "LCU per US$, annual average",
    kind: "rate",
    code: "PA.NUS.FCRF",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/PA.NUS.FCRF",
    decimals: 1,
  },
  {
    slug: "real-interest-rate",
    title: "Real interest rate",
    unit: "percent",
    kind: "pct",
    code: "FR.INR.RINR",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/FR.INR.RINR",
    decimals: 1,
  },
  {
    slug: "fiscal-balance",
    title: "Government fiscal balance",
    unit: "% of GDP",
    kind: "pct",
    code: "GC.NLD.TOTL.GD.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/GC.NLD.TOTL.GD.ZS",
    decimals: 1,
  },
  {
    slug: "public-debt",
    title: "Public debt (general government)",
    unit: "% of GDP",
    kind: "pct",
    code: "GGXWDG_NGDP",
    source: "IMF WEO",
    sourceUrl: "https://www.imf.org/en/Publications/WEO",
    decimals: 1,
    optional: true,
  },
  {
    slug: "fdi-inflows",
    title: "FDI net inflows",
    unit: "% of GDP",
    kind: "pct",
    code: "BX.KLT.DINV.WD.GD.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/BX.KLT.DINV.WD.GD.ZS",
    decimals: 1,
  },
  {
    slug: "manufacturing",
    title: "Manufacturing value added",
    unit: "% of GDP",
    kind: "pct",
    code: "NV.IND.MANF.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/NV.IND.MANF.ZS",
    decimals: 1,
  },
  {
    slug: "agriculture",
    title: "Agriculture value added",
    unit: "% of GDP",
    kind: "pct",
    code: "NV.AGR.TOTL.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/NV.AGR.TOTL.ZS",
    decimals: 1,
  },
  {
    slug: "gross-savings",
    title: "Gross savings",
    unit: "% of GDP",
    kind: "pct",
    code: "NY.GNS.ICTR.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/NY.GNS.ICTR.ZS",
    decimals: 1,
  },
  {
    slug: "debt-service",
    title: "External debt service",
    unit: "% of exports of goods, services and primary income",
    kind: "pct",
    code: "DT.TDS.DECT.EX.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/DT.TDS.DECT.EX.ZS",
    decimals: 1,
  },
  {
    slug: "unemployment",
    title: "Unemployment",
    unit: "% of labor force (ILO modelled)",
    kind: "pct",
    code: "SL.UEM.TOTL.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SL.UEM.TOTL.ZS",
    decimals: 1,
  },
  {
    slug: "female-labor-participation",
    title: "Female labor force participation",
    unit: "% of women 15+ (ILO modelled)",
    kind: "pct",
    code: "SL.TLF.CACT.FE.ZS",
    source: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SL.TLF.CACT.FE.ZS",
    decimals: 1,
  },
];

export const INDICATOR_MAP: Record<string, IndicatorMeta> = Object.fromEntries(
  INDICATORS.map((i) => [i.slug, i]),
);

// How the dossiers group the series, and how the compare pills are grouped, in
// reading order. One list, so a section cannot drift between the two pages.
export const INDICATOR_SECTIONS: { title: string; rows: string[][] }[] = [
  {
    title: "Growth & Output",
    rows: [["gdp-growth"], ["gdp-per-capita"]],
  },
  {
    title: "Prices & Money",
    rows: [["inflation", "broad-money"]],
  },
  {
    title: "Structure & jobs",
    rows: [["agriculture", "manufacturing"], ["unemployment", "female-labor-participation"]],
  },
  {
    title: "Investment & Debt",
    rows: [["gross-capital-formation", "gross-savings"], ["fdi-inflows", "debt-service"], ["external-debt"]],
  },
  {
    title: "External Sector",
    rows: [["exports", "imports", "current-account"], ["reserves-months", "remittances"]],
  },
  {
    title: "Fiscal & money",
    rows: [["fiscal-balance", "public-debt"], ["exchange-rate", "real-interest-rate"]],
  },
];

export const SECTION_BY_SLUG: Record<string, string> = Object.fromEntries(
  INDICATOR_SECTIONS.flatMap((s) => s.rows.flat().map((slug) => [slug, s.title])),
);