import { INDICATORS } from "@/lib/indicators";
import { loadMeta } from "@/lib/loaders";

export const metadata = {
  title: "Methodology & sources",
  description:
    "Where Macro Lens numbers come from, how they are measured, and what they do not claim.",
};

export default function MethodologyPage() {
  const meta = loadMeta();
  const updated =
    typeof meta?.lastUpdated === "string" ? meta.lastUpdated : "n/a";

  return (
    <div className="mx-auto w-full max-w-4xl px-4 pb-20 pt-12">
      <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#52B788]">
        Methodology
      </p>
      <h1 className="mt-2 text-3xl font-bold text-[#E8E8ED]">
        Where the numbers come from
      </h1>
      <p className="mt-3 text-sm leading-relaxed text-[#A0A0A8]">
        Macro Lens reports official time series from the{" "}
        <strong className="text-[#E8E8ED]">World Bank</strong> (World
        Development Indicators). Data is pulled programmatically, stored as
        static files in the repository, and regenerated by a single script
        (<code className="font-mono text-xs text-[#6ED49C]">pull.py</code>).
        No third-party aggregators, no curated spin.
      </p>

      <h2 className="mt-10 border-b border-[#1A1A20] pb-2 text-xs font-bold uppercase tracking-[0.18em] text-[#8A8A94]">
        Indicators & sources
      </h2>
      <div className="mt-4 overflow-x-auto">
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="border-b border-[#2A2A32] text-left text-[11px] uppercase tracking-wider text-[#8A8A94]">
              <th className="py-2 pr-3 font-semibold">Indicator</th>
              <th className="py-2 pr-3 font-semibold">Unit</th>
              <th className="py-2 pr-3 font-semibold">Series code</th>
              <th className="py-2 font-semibold">Publisher</th>
            </tr>
          </thead>
          <tbody>
            {INDICATORS.map((i) => (
              <tr
                key={i.slug}
                className="border-b border-[#1A1A20] text-[#A0A0A8]"
              >
                <td className="py-2 pr-3 font-medium text-[#E8E8ED]">
                  {i.title}
                </td>
                <td className="py-2 pr-3">{i.unit}</td>
                <td className="py-2 pr-3 font-mono text-xs">{i.code}</td>
                <td className="py-2">
                  <a
                    href={i.sourceUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="text-[#52B788] hover:text-[#6ED49C]"
                  >
                    {i.source}
                  </a>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h2 className="mt-10 border-b border-[#1A1A20] pb-2 text-xs font-bold uppercase tracking-[0.18em] text-[#8A8A94]">
        Reading the charts
      </h2>
      <ul className="mt-4 list-disc space-y-2 pl-5 text-sm leading-relaxed text-[#A0A0A8]">
        <li>
          <strong className="text-[#E8E8ED]">The solid line</strong> is the
          country you opened. When &quot;show peers&quot; is on, the other four
          countries appear in grey for context, same source, same unit, same
          scale.
        </li>
        <li>
          Level series (GDP per capita, reserves) use a linear axis; percent
          series are shown as reported. Missing years render as real gaps,
          never interpolation.
        </li>
        <li>
          Chart titles state the finding the data shows, not just what was
          plotted. Where the claim is a comparison (e.g. &quot;below the 3-month
          danger line&quot;), it is computed from the same underlying series on
          display.
        </li>
      </ul>

      <h2 className="mt-10 border-b border-[#1A1A20] pb-2 text-xs font-bold uppercase tracking-[0.18em] text-[#8A8A94]">
        Caveats & limitations
      </h2>
      <ul className="mt-4 list-disc space-y-2 pl-5 text-sm leading-relaxed text-[#A0A0A8]">
        <li>
          <strong className="text-[#E8E8ED]">Revision risk.</strong> WDI and WEO
          revise historical values as methodologies and national accounts change
          (base-year shifts, rebasing). The site is refreshed from the live APIs,
          so snapshots differ slightly from earlier vintages.
        </li>
        <li>
          <strong className="text-[#E8E8ED]">Coverage gaps.</strong> Some series
          start later or end earlier for some countries (e.g. real interest
          rates and reserve coverage vary). Gaps are shown, never filled in.
        </li>
        <li>
          <strong className="text-[#E8E8ED]">No causality claims.</strong> These
          charts compare. &quot;X happened before Y&quot; is description, not
          evidence that X caused Y. Read the patterns as questions, not verdicts.
        </li>
        <li>
          <strong className="text-[#E8E8ED]">Cross-country comparability.</strong>{" "}
          Definitions differ slightly across publishers and vintages; sharing one
          publisher per series keeps each comparison internally consistent.
        </li>
        <li>
          <strong className="text-[#E8E8ED]">This is not investment advice</strong>{" "}
          and not a forecast. The series shown are historical outcomes.
        </li>
      </ul>

      <p className="mt-10 rounded-xl border border-[#1A1A20] bg-[#111115] p-4 text-xs leading-relaxed text-[#8A8A94]">
        Last updated from source APIs:{" "}
        <span className="text-[#A0A0A8]">{updated}</span>. The full pipeline and
        data files are public in the repository. Every number on this site can
        be reproduced by running{" "}
        <code className="font-mono text-xs text-[#6ED49C]">pull.py</code> and
        rebuilding.
      </p>
    </div>
  );
}