import { ALL_COUNTRIES, COUNTRY_MAP } from "@/lib/countries";
import { INDICATOR_MAP, INDICATORS } from "@/lib/indicators";
import { coverageSpan, loadMeta, loadSeries } from "@/lib/loaders";
import type { CountrySlug } from "@/lib/types";

export const metadata = {
  title: "Methodology & sources",
  description:
    "Where Macro Lens numbers come from, how they are measured, and what they do not claim.",
};

export default function MethodologyPage() {
  const meta = loadMeta();
  const updated =
    typeof meta?.lastUpdated === "string" ? meta.lastUpdated : "n/a";

  // Read straight off the shipped files, so this table cannot claim more coverage
  // than the data has.
  const coverage = INDICATORS.map((ind) => {
    const cells = ALL_COUNTRIES.map((c) => ({
      c,
      span: coverageSpan(loadSeries(c.slug, ind.slug)),
    }));
    const latest = Math.max(0, ...cells.map((x) => x.span?.last ?? 0));
    return { ind, cells, latest };
  });

  // The pipeline compares each refresh with the vintage on disk, so the site can
  // say what moved instead of only warning that things move. Absent on an old
  // meta.json, which is why it is read defensively and rendered only if present.
  const refreshedOn =
    typeof meta?.generatedAt === "string" ? meta.generatedAt : updated;
  const rev = (meta?.revisions ?? null) as {
    changed: number;
    compared: number;
    largest: {
      series: string;
      country: string;
      year: number;
      from: number;
      to: number;
    } | null;
  } | null;
  const revisionNote =
    rev && typeof rev.changed === "number" && typeof rev.compared === "number"
      ? rev.changed === 0
        ? `The refresh of ${refreshedOn} re-derived ${rev.compared.toLocaleString("en-US")} observations and revised none of them.`
        : `The refresh of ${refreshedOn} re-derived ${rev.compared.toLocaleString("en-US")} observations and revised ${rev.changed}${
            rev.largest
              ? `, the largest being ${COUNTRY_MAP[rev.largest.country as CountrySlug]?.name ?? rev.largest.country} ${INDICATOR_MAP[rev.largest.series]?.title ?? rev.largest.series} in ${rev.largest.year}, from ${rev.largest.from} to ${rev.largest.to}`
              : ""
          }.`
      : null;

  return (
    <div className="mx-auto w-full max-w-4xl px-4 pb-20 pt-12">
      <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#52B788]">
        Methodology
      </p>
      <h1 className="mt-2 text-3xl font-bold text-[#E8E8ED]">
        Where the numbers come from
      </h1>
      <p className="mt-3 text-sm leading-relaxed text-[#A0A0A8]">
        Macro Lens reports official time series from the{" "}
        <strong className="text-[#E8E8ED]">World Bank</strong> (World
        Development Indicators) and the{" "}
        <strong className="text-[#E8E8ED]">IMF</strong> (World Economic
        Outlook, for general-government public debt). Data is pulled
        programmatically, stored as static files in the repository, and
        regenerated by a single script
        (<code className="font-mono text-xs text-[#6ED49C]">pull.py</code>).
        No third-party aggregators, no curated spin.
      </p>

      <h2 className="mt-10 border-b border-[#1A1A20] pb-2 text-xs font-bold uppercase tracking-[0.18em] text-[#8A8A94]">
        Indicators & sources
      </h2>
      <div className="mt-4 overflow-x-auto">
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="border-b border-[#2A2A32] text-left text-[11px] uppercase tracking-wider text-[#8A8A94]">
              <th className="py-2 pr-3 font-semibold">Indicator</th>
              <th className="py-2 pr-3 font-semibold">Unit</th>
              <th className="py-2 pr-3 font-semibold">Series code</th>
              <th className="py-2 font-semibold">Publisher</th>
            </tr>
          </thead>
          <tbody>
            {INDICATORS.map((i) => (
              <tr
                key={i.slug}
                className="border-b border-[#1A1A20] text-[#A0A0A8]"
              >
                <td className="py-2 pr-3 font-medium text-[#E8E8ED]">
                  {i.title}
                </td>
                <td className="py-2 pr-3">{i.unit}</td>
                <td className="py-2 pr-3 font-mono text-xs">{i.code}</td>
                <td className="py-2">
                  <a
                    href={i.sourceUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="text-[#52B788] hover:text-[#6ED49C]"
                  >
                    {i.source}
                  </a>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h2 className="mt-10 border-b border-[#1A1A20] pb-2 text-xs font-bold uppercase tracking-[0.18em] text-[#8A8A94]">
        What the data covers
      </h2>
      <p className="mt-3 text-xs leading-relaxed text-[#8A8A94]">
        The first and last year each series actually has an observation for, by
        country. An asterisk marks a series that stops earlier here than it does
        for the best-covered country in that row; interior gaps are shown on the
        charts and never interpolated. Two-letter codes match the header.
      </p>
      <div className="mt-4 overflow-x-auto">
        <table className="w-full border-collapse text-xs">
          <thead>
            <tr className="border-b border-[#2A2A32] text-left text-[11px] uppercase tracking-wider text-[#8A8A94]">
              <th className="py-2 pr-3 font-semibold">Series</th>
              {ALL_COUNTRIES.map((c) => (
                <th key={c.slug} className="py-2 pr-3 font-semibold">
                  {c.short}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {coverage.map(({ ind, cells, latest }) => (
              <tr key={ind.slug} className="border-b border-[#1A1A20] text-[#A0A0A8]">
                <td className="py-2 pr-3 font-medium text-[#E8E8ED]">{ind.title}</td>
                {cells.map(({ c, span }) => (
                  <td key={c.slug} className="py-2 pr-3 font-mono">
                    {span
                      ? `${span.first}-${span.last}${span.last < latest ? "*" : ""}`
                      : "none"}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h2 className="mt-10 border-b border-[#1A1A20] pb-2 text-xs font-bold uppercase tracking-[0.18em] text-[#8A8A94]">
        Reading the charts
      </h2>
      <ul className="mt-4 list-disc space-y-2 pl-5 text-sm leading-relaxed text-[#A0A0A8]">
        <li>
          <strong className="text-[#E8E8ED]">The solid line</strong> is the
          country you opened. When &quot;show peers&quot; is on, the other four
          South Asian countries appear in grey, and Vietnam and Indonesia, kept
          as benchmarks, in dashed grey, all from the same publishers, same
          units, same scale.
        </li>
        <li>
          <strong className="text-[#E8E8ED]">Benchmarks stay out of the
          verdicts.</strong> The generated findings rank a country against its
          five South Asian neighbours only. Vietnam and Indonesia are there to
          read the scale of a number, never counted as neighbours in the prose
          or in the regional ranges.
        </li>
        <li>
          Level series (GDP per capita, reserves) use a linear axis; percent
          series are shown as reported. Missing years render as real gaps,
          never interpolation.
        </li>
        <li>
          <strong className="text-[#E8E8ED]">Chart titles are generated, not typed.</strong>{" "}
          Every title and summary line is computed at build time from the same
          data files the chart plots. When the data refreshes, the findings
          regenerate with it, and a test suite re-derives every statistic the
          prose cites and fails if a number cannot be traced to the series on
          display.
        </li>
      </ul>

      <h2 className="mt-10 border-b border-[#1A1A20] pb-2 text-xs font-bold uppercase tracking-[0.18em] text-[#8A8A94]">
        Caveats & limitations
      </h2>
      <ul className="mt-4 list-disc space-y-2 pl-5 text-sm leading-relaxed text-[#A0A0A8]">
        <li>
          <strong className="text-[#E8E8ED]">Revision risk.</strong> WDI and WEO
          revise historical values as methodologies and national accounts change
          (base-year shifts, rebasing). The site is refreshed from the live APIs,
          so snapshots differ slightly from earlier vintages.
          {revisionNote && <> {revisionNote}</>}
        </li>
        <li>
          <strong className="text-[#E8E8ED]">Coverage gaps.</strong> Some series
          start later or end earlier for some countries (e.g. real interest
          rates and reserve coverage vary). Gaps are shown, never filled in.
        </li>
        <li>
          <strong className="text-[#E8E8ED]">No causality claims.</strong> These
          charts compare. &quot;X happened before Y&quot; is description, not
          evidence that X caused Y. Read the patterns as questions, not verdicts.
        </li>
        <li>
          <strong className="text-[#E8E8ED]">Cross-country comparability.</strong>{" "}
          Definitions differ slightly across publishers and vintages; sharing one
          publisher per series keeps each comparison internally consistent.
        </li>
        <li>
          <strong className="text-[#E8E8ED]">This is not investment advice</strong>{" "}
          and not a forecast. The series shown are historical outcomes.
        </li>
        <li>
          <strong className="text-[#E8E8ED]">Two debt measures.</strong> External
          debt (World Bank) covers only debt owed to nonresidents, as a share of
          GNI. Public debt (IMF) is total general-government debt, domestic plus
          external, as a share of GDP. They are different gauges and are never
          added together here.
        </li>
        <li>
          <strong className="text-[#E8E8ED]">Modelled estimates.</strong>{" "}
          Unemployment and female labor force participation are ILO modelled
          estimates published through WDI, not national survey counts: they are
          built to be comparable across countries, not to measure any one labor
          market exactly. External debt service is shown as a share of exports
          of goods, services and primary income, so it moves with export
          earnings as well as with the debt itself.
        </li>
        <li>
          <strong className="text-[#E8E8ED]">Averages and completed years.</strong>{" "}
          The exchange rate is the official period-average rate from WDI, an
          annual average rather than a spot rate. The IMF public-debt series is
          truncated to completed calendar years, so no projections appear.
        </li>
      </ul>

      <p className="mt-10 rounded-xl border border-[#1A1A20] bg-[#111115] p-4 text-xs leading-relaxed text-[#8A8A94]">
        Last updated from source APIs:{" "}
        <span className="text-[#A0A0A8]">{updated}</span>. The full pipeline and
        data files are public in the repository. Every number on this site can
        be reproduced by running{" "}
        <code className="font-mono text-xs text-[#6ED49C]">pull.py</code> and
        rebuilding.
      </p>
    </div>
  );
}